#employer analysis

ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_PRIMARY <- str_trim(ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_PRIMARY)
ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_SECOND <- str_trim(ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_SECOND)
ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_THIRD <- str_trim(ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_THIRD)

sum(ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_THIRD != '' | ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_SECOND !='' )
sum(ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_PRIMARY !='')
sum(is.na(ifm_201410$INTELLIGENTSIA_EMPLOYER_NAME_PRIMARY ))


employers <- ifm_201410 %>% select(INTELLIGENTSIA_ID:EXPRESSION_1,INTELLIGENTSIA_EMPLOYER_NAME_PRIMARY:INTELLIGENTSIA_EMPLOYER_NAME_THIRD) %>% 
  gather(measure,employer,INTELLIGENTSIA_EMPLOYER_NAME_PRIMARY:INTELLIGENTSIA_EMPLOYER_NAME_THIRD) %>% 
  filter(employer!='')


employers <- left_join(employers,hhlds_201410[c('HHLD_ID','HHLD_HHLD_STATE','HHLD_COMMUNITY_BANK_MARKET')],by=c('INTELLIGENTSIA_ID' = 'HHLD_ID'))


employers %>% filter(HHLD_COMMUNITY_BANK_MARKET %in% c('1','12','17')) %>% group_by(HHLD_COMMUNITY_BANK_MARKET,employer) %>%
  summarise(N=n_distinct(EXPRESSION_1)) %>% arrange(desc(N)) %>% mutate(indx=1:n()) %>% filter(indx <= 15)
  

save(employers,file='employers.rdata')
